name: Algorithms
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Unit Tests
    name: Unit Tests
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch for build
        uses: actions/checkout@master
      - name: Setup python version
        uses: actions/setup-python@v1
        with:
          python-version: '>3.5'
          architecture: x64
      - name: Install dependencies
        run: |
                python setup.py install
                pip install nose
                pip install coverage
      - name: Unit Tests
        run: python setup.py nosetests --cover-package HackerRank --cover-package CareerCup --cover-package interviews --with-coverage
        env:
          RUN_EXPENSIVE_TESTS: True