name: Algorithms
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  python:
    name: Python Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch for build
        uses: actions/checkout@master
      - name: Setup python version
        uses: actions/setup-python@v1
        with:
          python-version: '>3.5'
          architecture: x64
      - name: Install dependencies
        run: |
                python setup.py install
                pip install nose
                pip install coverage
      - name: Unit Tests
        run: python setup.py nosetests --cover-package CareerCup,HackerRank,interviews --with-coverage
        env:
          RUN_EXPENSIVE_TESTS: True

  go:
    name: GoLang Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch for build
        uses: actions/checkout@master
      - name: Setup python version
        uses: actions/setup-go@v1
        with:
          go-version: '>1.12'
      - name: Unit Tests
        run: go test -json ./...